### ISSUE TITLE
Stomp commands and header names should be case sensitive

### ISSUE THREAD

**Issue by francma** [hozn/coilmq#23]
From https://stomp.github.io/stomp-specification-1.2.html

> All commands and header names referenced in this document are case sensitive.

This causes incompatibility with some Stomp clients allowing only upper cased commands (as defined in specification).

Stompest for example:
`DEBUG:stompest.async.listener:Calling disconnected errback: Unexpected connection loss [Invalid command (version 1.1): 'message']`

**Comment by ZhukovAlexander** [comment]
Thanks for reporting this issue, I'll take a look at the nearest time.
